name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  repo-token:  # id of input
    description: 'Github auth token'
    required: true
# inputs:
#   who-to-greet:  # id of input
#     description: 'Who to greet'
#     required: true
#     default: 'World'
#   team:  # id of input
#     description: 'Team Name'
#     required: true
# outputs:
#   time: # id of output
#     description: 'The time we greeted you'
runs:
  using: 'node12'
  main: 'dist/index.js'